// Plain data — no client/server markers, importable from anywhere
export const BLOG_POSTS = [
  { id: '1', slug: 'graduation-ceremony-2025', title_en: 'ZTF University Institute Celebrates Successful 2025 Graduation Ceremony', title_fr: "L'Institut Universitaire ZTF Célèbre la Cérémonie de Remise de Diplômes 2025", excerpt_en: 'ZTF University Institute celebrated its annual graduation ceremony with over 100 graduates receiving their degrees and certificates in Bertoua, Cameroon. Special prizes were awarded to distinguished graduates.', excerpt_fr: "L'Institut Universitaire ZTF a célébré sa cérémonie annuelle de remise de diplômes avec plus de 100 diplômés à Bertoua. Des prix spéciaux ont été remis aux diplômés distingués.", date: '2025-07-15', category: 'news', cat_en: 'University News', cat_fr: 'Actualités Universitaires', image: '/images/1.jpg', author: 'ZTF University Communications', readTime: 3 },
  { id: '2', slug: 'admissions-open-2026-2027', title_en: 'Admissions Now Open for Academic Year 2026–2027', title_fr: "Ouverture des Inscriptions pour l'Année Académique 2026–2027", excerpt_en: 'ZTF University Institute is pleased to announce that admissions for the 2026–2027 academic year are now officially open across all programmes in our 3 Higher Institutes, 7 Schools, and 2 Vocational Training Institutes.', excerpt_fr: "L'Institut Universitaire ZTF a le plaisir d'annoncer l'ouverture officielle des inscriptions pour l'année académique 2026–2027 dans tous les programmes.", date: '2026-03-01', category: 'admissions', cat_en: 'Admissions', cat_fr: 'Admissions', image: '/images/4.jpg', author: 'Admissions Office', readTime: 2 },
  { id: '3', slug: 'national-day-parade-2025', title_en: 'IU-ZTF Students Represent the University at National Day Parade in Bertoua', title_fr: "Les Étudiants de l'IU-ZTF Représentent l'Université au Défilé de la Fête Nationale", excerpt_en: 'IU-ZTF students proudly marched through the streets of Bertoua in their university blue polo shirts, holding the Cameroonian flag during the national day celebration, drawing widespread admiration.', excerpt_fr: "Les étudiants de l'IU-ZTF ont fièrement défilé dans les rues de Bertoua en portant leurs polos bleus universitaires et le drapeau du Cameroun lors de la fête nationale.", date: '2025-05-20', category: 'student_life', cat_en: 'Student Life', cat_fr: 'Vie Étudiante', image: '/images/5.jpg', author: 'Student Affairs Office', readTime: 2 },
  { id: '4', slug: 'ztf-legacy-excellence', title_en: "The Legacy of Prof. Zacharias Tanee Fomum: Building Excellence in African Education", title_fr: "L'Héritage du Prof. Zacharias Tanee Fomum : Bâtir l'Excellence dans l'Éducation Africaine", excerpt_en: "Professor Zacharias Tanee Fomum (1945–2009) was one of Africa's greatest academic minds. With over 160 publications, 100+ supervised theses, and a Doctor of Science from Durham University, his legacy lives on at ZTF University Institute.", excerpt_fr: "Le Professeur Zacharias Tanee Fomum (1945–2009) était l'un des plus grands esprits académiques d'Afrique. Avec plus de 160 publications et 100+ thèses supervisées, son héritage continue d'inspirer l'IU-ZTF.", date: '2025-01-14', category: 'faith', cat_en: 'Faith & Learning', cat_fr: 'Foi & Apprentissage', image: '/images/Founder.jpeg', author: 'Editorial Team', readTime: 5 },
  { id: '5', slug: 'wcs-research-partnership', title_en: 'ZTF University Partners with World Conquest Science for Research Development', title_fr: "L'IU-ZTF s'associe à World Conquest Science pour le Développement de la Recherche", excerpt_en: 'ZTF University Institute has formalized its academic partnership with World Conquest Science (WCS). This collaboration advances research in tropical medicinal plants, drug development, and scientific education in Cameroon.', excerpt_fr: "L'Institut Universitaire ZTF a formalisé son partenariat académique avec World Conquest Science (WCS). Cette collaboration fait avancer la recherche en plantes médicinales tropicales.", date: '2025-09-10', category: 'research', cat_en: 'Research', cat_fr: 'Recherche', image: '/images/2.jpg', author: 'Research Office', readTime: 3 },
  { id: '6', slug: 'new-school-health-professions', title_en: 'ZTF University Establishes School of Health Professions (SHP/EMS)', title_fr: "L'IU-ZTF crée l'École des Métiers de la Santé (EMS)", excerpt_en: 'ZTF University Institute announces the establishment of the School of Health Professions (SHP/EMS), a specialized professional school dedicated to training highly skilled health professionals in hands-on, competency-based programmes.', excerpt_fr: "L'Institut Universitaire ZTF annonce la création de l'École des Métiers de la Santé (EMS), une école professionnelle spécialisée dédiée à la formation de professionnels de santé.", date: '2026-01-20', category: 'news', cat_en: 'University News', cat_fr: 'Actualités Universitaires', image: '/images/3.jpg', author: 'Office of the Rector', readTime: 2 },
];

export type BlogPost = typeof BLOG_POSTS[0];
